#!/usr/bin/env python3
"""Task 3 reclassification (reproducible). Reads docs/audit/item_audit.json and writes docs/registry_item_audit_p7.py (applied by docs/build_registry.py).
Rules (a status is only ever LOWERED here, never raised, and every change keeps the old evidence text):
  R1  EXISTS_AND_WORKING -> PARTIAL when the module is only imported into the integration-hub adapter bag (HUB_ADAPTER_BAG_ONLY) or not reachable at all:
      no production workflow invokes it, so 'working' is not supported.  Exception R2.
  R2  S13-008..012 and S48-011 (no unauthorized subscription/purchase/payment/banking/contract/loan) stay EXISTS_AND_WORKING, but their evidence is RE-POINTED from the
      unconnected guardrail-engine to the control chain that really enforces them (probe: docs/audit/independent_probes.mjs P04/P05; atlasz-tests/owner-control-core.test.mjs)."""
import json, os
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
A = json.load(open(os.path.join(root, "docs/audit/item_audit.json"), encoding="utf-8"))
REG = {x["id"]: x for x in json.load(open(os.path.join(root, "docs/atlasz_v73_requirement_registry.json"), encoding="utf-8"))["requirements"]}
KEEP_REPOINT = {"V73-S13-008", "V73-S13-009", "V73-S13-010", "V73-S13-011", "V73-S13-012", "V73-S48-011"}
out = {}; down = []
for r in A:
    if r["registry_status"] != "EXISTS_AND_WORKING" or r["level"] != "item": continue
    f = set(r["flags"]); x = REG[r["id"]]
    if r["id"] in KEEP_REPOINT:
        out[r["id"]] = dict(status="EXISTS_AND_WORKING", implementation_location="atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
            tests=["atlasz-tests/owner-control-core.test.mjs", "atlasz-tests/owner-control-bypass.test.mjs"],
            evidence=["TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: " + (x.get("evidence") or [""])[0][:200]],
            blocker="SANDBOX evidence only: no real owner key or live channel exercised")
        continue
    if f & {"MODULE_TESTED_BUT_NEVER_INVOKED_BY_A_RUNTIME_WORKFLOW", "MODULE_NOT_REACHABLE_FROM_RUNTIME_CC_CLI"}:
        why = "module is imported only into the integration-hub adapter bag and no production workflow invokes it" if "MODULE_TESTED_BUT_NEVER_INVOKED_BY_A_RUNTIME_WORKFLOW" in f else "module is not reachable from the runtime, Control Center or owner CLI"
        out[r["id"]] = dict(status="PARTIAL", evidence=["TASK3 downgrade from EXISTS_AND_WORKING: " + why + ". Unit-level behaviour is tested; it is not part of a running workflow. Previous evidence: " + (x.get("evidence") or [""])[0][:220]],
            blocker="Module tested in isolation; needs a runtime workflow that invokes it (or removal if it duplicates a connected implementation)")
        down.append(r["id"])
# IDEMPOTENCE (fixed in Task 4): item_audit.json only sets flags on rows that are *currently* EXISTS_AND_WORKING, so a row downgraded by the previous run has no flags on the next
# run and would silently flip back to EXISTS_AND_WORKING (then back again on the run after). Carry earlier downgrades over; they are lifted only by a deliberate edit of a later registry_item_audit_p*.py or registry_new_*.py.
import importlib.util
_old = os.path.join(root, "docs/registry_item_audit_p7.py")
if os.path.exists(_old):
    _spec = importlib.util.spec_from_file_location("p7_prev", _old); _m = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_m)
    for _id, _v in _m.I.items():
        if _id not in out and _v.get("status") == "PARTIAL": out[_id] = _v; down.append(_id)
body = "# Task 3 reclassification (generated by docs/audit/reclassify.py - do not hand-edit). Statuses are only lowered here; evidence text is preserved.\nI = " + json.dumps(out, indent=1, ensure_ascii=False) + "\n"
open(os.path.join(root, "docs/registry_item_audit_p7.py"), "w", encoding="utf-8").write(body)
print("downgraded", len(down), down); print("repointed", len(KEEP_REPOINT))
