#!/usr/bin/env python3
"""Renders docs/TASK3_AUDIT_REPORT.md and docs/TASK3_ROADMAP.md from the generated audit data (numbers are never typed by hand)."""
import json, csv, os
from collections import Counter
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
J = lambda p: json.load(open(os.path.join(root, p), encoding="utf-8"))
rec = J("docs/audit/reconciliation.json"); road = J("docs/audit/roadmap.json"); ss = J("docs/audit/static_scan.json"); dyn = J("docs/audit/dynamic_probe.json"); pr = J("docs/audit/independent_probes.json")["results"]
tr = J("docs/audit/test_results.json"); cap = J("docs/atlasz_capability_audit_85.json")["capabilities"]; ia = J("docs/audit/item_audit.json")
cov = J("docs/audit/coverage_summary.json") if os.path.exists(os.path.join(root, "docs/audit/coverage_summary.json")) else None
rows = list(csv.DictReader(open(os.path.join(root, "docs/audit/open_items_detail.csv"), encoding="utf-8")))
BEFORE = dict(reg=dict(EXISTS_AND_WORKING=211, PARTIAL=478, MISSING=194, STRUCTURAL_ONLY=36, EXISTS_NEEDS_TEST=17, EXTERNAL_BLOCKER=35, BLOCKED_AWAITING_JOCI_APPROVAL=3), cap=dict(VERIFIED_WORKING=6, PARTIAL=47, MISSING=10, EXTERNAL_BLOCKER=22), gaps=792, gap_src=dict(REGISTRY=710, CAPABILITY_85=79, IMPORT_SCAN=3))
now = rec["registry_status_all"]; tsum = lambda k: sum(v[k] for v in tr.values())
def tbl(h, rs): return "\n".join(["| " + " | ".join(h) + " |", "|" + "---|" * len(h)] + ["| " + " | ".join(str(c) for c in r) + " |" for r in rs])
P = []
w = P.append
w("# ATLASZ V7.3 — Task 3: Technical audit and gap assessment\n")
w("Branch `atlasz-v73-integration`. Audit only: no product code was changed in Task 3 (only registry/audit data and audit tooling). Everything below is **SANDBOX evidence**: no live provider, credential, real owner key, Windows host, or production system was used, so **nothing is LIVE_VERIFIED**.\n")
w("## 1. Method and limits\n")
w("- Every one of the %d registry rows (%d items + %d section roll-ups) was mechanically checked (`docs/audit/item_audit.py`): do the named files exist, do the listed tests exist and pass, does a passing test actually name the module, is the module reachable from the runtime / Control Center / CLI, and is it *invoked* by production code (not just imported)." % (rec["registry_rows"], rec["by_level"]["item"], rec["by_level"]["section"]))
w("- The %d previously 'working' items were re-verified three ways: the mechanical scan, 20 independent probes that drive the real modules with attack-style input outside the unit tests (`independent_probes.mjs`), and a live boot of the runtime + Control Center that hits every route (`dynamic_probe.mjs`)." % BEFORE["reg"]["EXISTS_AND_WORKING"])
w("- Provenance: `docs/audit/` (static scan, item audit, per-file test runner) was already present, untracked, in the working tree when Task 3 began; it was not written in this session. Its stored outputs were discarded and every scan was re-run; `dynamic_probe.mjs`, `independent_probes.mjs`, `reclassify.py`, `roadmap.py` and `render_reports.py` were added in Task 3.")
w("- **Limits:** the scans are static (regex/import-graph), so dynamic `import()`, string-built tool names and runtime registration can be missed; 'invoked' means an import plus a call site was found, not that the call happens in practice. Passing tests prove behaviour in a sandbox, not real-world operation. The Windows installer, Railway, real providers, real money flows and a real owner key were not exercised. Hungarian-language requirement text was classified by its registry fields, not re-read from the spec line by line.\n")
w("## 2. Before and after\n")
w(tbl(["Registry rows", "Before Task 3", "After Task 3", "Change"], [[k, BEFORE["reg"][k], now.get(k, 0), "%+d" % (now.get(k, 0) - BEFORE["reg"][k])] for k in BEFORE["reg"]] + [["**Total rows**", 974, rec["registry_rows"], "%+d" % (rec["registry_rows"] - 974)]]))
w("\n" + tbl(["85 capabilities", "Before", "After", "Change"], [[k, BEFORE["cap"].get(k, 0), rec["capability"].get(k, 0), "%+d" % (rec["capability"].get(k, 0) - BEFORE["cap"].get(k, 0))] for k in ["VERIFIED_WORKING", "PARTIAL", "MISSING", "EXTERNAL_BLOCKER"]]))
gs = rec["gap_register_by_source"]
w("\n" + tbl(["Master gap register", "Before", "After", "Change"], [["REGISTRY item gaps", BEFORE["gap_src"]["REGISTRY"], gs["REGISTRY"], "%+d" % (gs["REGISTRY"] - BEFORE["gap_src"]["REGISTRY"])], ["CAPABILITY_85 gaps", BEFORE["gap_src"]["CAPABILITY_85"], gs["CAPABILITY_85"], "%+d" % (gs["CAPABILITY_85"] - BEFORE["gap_src"]["CAPABILITY_85"])], ["IMPORT_SCAN orphans", 3, gs["IMPORT_SCAN"], "+0"], ["**Total**", BEFORE["gaps"], rec["gap_register_total"], "%+d" % (rec["gap_register_total"] - BEFORE["gaps"])]]))
w("\n**What the change means.** Nothing was newly built and no gap was closed in Task 3. The open-gap count rose by %d = 23 registry items + 3 capabilities **reclassified downward** (their 'working' status was not supported: modules are tested but nothing runs them; these are over-claims, not new problems) + %d **newly discovered** gaps registered as ATLASZ-T3-001..009 (8 MISSING, 1 EXTERNAL_BLOCKER): unauthenticated runtime dashboard, unsandboxed plugin/update child processes, agents cannot invoke tools, duplicate/hub-bag-only modules, weak-random id fallbacks, no restore UI, 4 untested routes, no schedule creation in the UI, unverified real-source discovery.\n" % (rec["gap_register_total"] - BEFORE["gaps"], 9))
w("## 3. Reconciliation: requirements vs gaps (no double counting)\n")
w("The three documents measure different things and overlap. Rule used: **a requirement is a registry item of kind PRODUCT or SUPPLEMENTARY; a gap is a requirement (or capability) that is not IMPLEMENTED.** Section roll-ups, status-vocabulary labels, process/audit tasks and implementation records are tracked but are not counted as outstanding product requirements.\n")
kinds = rec["by_kind"]
w(tbl(["Registry row kind", "Rows", "Open (not implemented)", "Counted as outstanding product requirement?"], [[k, kinds[k], rec["open_items_by_kind"].get(k, 0) if k != "SECTION_ROLLUP" else sum(1 for r in rows if r["kind"] == k and r["final_class"] != "IMPLEMENTED"), {"PRODUCT_REQUIREMENT": "yes", "SUPPLEMENTARY_REQUIREMENT": "yes (Joci addenda: ATLASZ-BR/OSC/UC/CR/CC/SV)", "SECTION_ROLLUP": "no (derived from its items; counted once via the items)", "STATUS_LABEL": "no (S12 vocabulary words, not behaviour)", "PROCESS_OR_AUDIT_TASK": "no (S42/S43/S44/S50 working-method and audit-task items)", "IMPLEMENTATION_RECORD": "no (ATLASZ-PKG84: records of work already done; the requirement they implement is counted elsewhere)"}[k]] for k in ["PRODUCT_REQUIREMENT", "SUPPLEMENTARY_REQUIREMENT", "SECTION_ROLLUP", "STATUS_LABEL", "PROCESS_OR_AUDIT_TASK", "IMPLEMENTATION_RECORD"]]))
w("\n- **974 rows = %d items + %d section roll-ups.** The registry figures quoted at the start of Task 3 (478 PARTIAL / 194 MISSING; now 501 / 194 after the 23 downgrades) include roll-ups: at item level it is %d PARTIAL (+%d STRUCTURAL_ONLY, +%d EXISTS_NEEDS_TEST, which this audit also reports as PARTIAL) and %d MISSING." % (rec["by_level"]["item"], rec["by_level"]["section"], rec["registry_status_items"]["PARTIAL"], rec["registry_status_items"]["STRUCTURAL_ONLY"], rec["registry_status_items"]["EXISTS_NEEDS_TEST"], rec["registry_status_items"]["MISSING"]))
w("- **Unique outstanding requirements: %d** (%d product + %d supplementary, not implemented). The remaining open registry rows are %d roll-ups/labels/process tasks/implementation records." % (rec["unique_open_requirements"], rec["open_items_by_kind"]["PRODUCT_REQUIREMENT"], rec["open_items_by_kind"]["SUPPLEMENTARY_REQUIREMENT"], rec["open_items"] - rec["unique_open_requirements"]))
w("- **Gap register total %d = %s.** Every REGISTRY gap links to exactly one registry item; each CAPABILITY gap links to the registry items it depends on (`depends_on`). %d of the %d open capabilities link to registry items, so most capability gaps are *views of the same work*, not additional work; only %s have no registry link and are independent." % (rec["gap_register_total"], rec["gap_register_formula"], rec["capability_open_linked_to_registry"], rec["capability_open"], ", ".join(rec["capability_open_without_link"])))
w("- Therefore the honest size of the remaining work is **~%d requirements** (not %d gaps and not 974); the %d-gap figure double counts capability views and non-product rows. Dangling capability→registry links: %d.\n" % (rec["unique_open_requirements"] + len(rec["capability_open_without_link"]), rec["gap_register_total"], rec["gap_register_total"], len(rec["capability_dangling_links"])))
w("Final classification of all %d items (registry status mapped to the five classes requested; STRUCTURAL_ONLY and EXISTS_NEEDS_TEST are reported as PARTIAL; **no item is LIVE-verified**):\n" % rec["by_level"]["item"])
w(tbl(["Class", "Items"], [[k, v] for k, v in sorted(rec["items_by_class"].items(), key=lambda kv: -kv[1])]))
w("\n## 4. Verification of the previously 'working' items\n")
w("Started with **211** EXISTS_AND_WORKING registry rows (all items).")
fl = Counter(f for r in ia if r["registry_status"] == "EXISTS_AND_WORKING" for f in r["flags"])
w("\n| Outcome | Count | Detail |\n|---|---|---|\n| Retained as EXISTS_AND_WORKING | %d | sandbox-verified; none LIVE |\n| Downgraded to PARTIAL | 23 | module tested but imported only into the integration-hub adapter bag / unreachable; no workflow invokes it (S03-005, S03-011, S07-013, S09-026, S11-003/007/010/011/012/014, S15-002/004/006/007/009/011, S16-002/003/005/006, S27-009, S29-012, S50-005) |\n| Retained, evidence re-pointed | 6 | S13-008..012 and S48-011 (no unauthorized subscription/purchase/payment/banking/contract/loan) were credited to the unconnected guardrail-engine; the real enforcer is the runtime control chain. Re-verified by probe P04/P05 |\n" % now["EXISTS_AND_WORKING"])
w("Remaining flags on retained items (reviewed, none changes status): %s. These are meta items (tests/registry/audit-task rows with no code module), a `*.test.mjs` glob mistaken for a missing file (ATLASZ-CR-003), or heuristic misses where the test drives a real process (S14-001, S35-008)." % ", ".join("%s×%d" % kv for kv in fl.items()))
w("\n**Independent probes (20):** " + "%d/%d pass.\n" % (sum(1 for p in pr if p["ok"]), len(pr)))
w(tbl(["Probe", "Claim", "Result"], [[p["id"], p["claim"], "PASS" if p["ok"] else "FAIL"] for p in pr]))
w("\n**Live boot of runtime + Control Center:** %d agents (%s); %d typed tools registered; %d Control Center routes (%d GET, %d POST): every GET returns 200 with a token and is refused without one, every POST is refused without/with a wrong token, a foreign Host header gets %s. " % (dyn["runtime"]["agents"], ", ".join("%s %d" % kv for kv in dyn["runtime"]["teams"].items()), len(dyn["runtime"]["tools"]), len(dyn["routes"]), sum(1 for v in dyn["routes"].values() if v["method"] == "GET"), sum(1 for v in dyn["routes"].values() if v["method"] == "POST"), dyn["hostRebinding"]))
w("\n### 85 capabilities re-verified\n")
w("3 of the 6 'VERIFIED_WORKING' capabilities were downgraded: **G06 Function Calling, GE08 Structured Tool Invocation, P14 Strict Structured Output** — the schema/permission layer is verified, but no agent or model invokes the tools (only the scheduler and tests do), so the capability is not working end to end. C11 stays verified but its evidence no longer relies on the by-design-unwired `tenant-isolation.mjs` or the in-memory demo RAG. C12 (scheduler) and C13 (owner administration/security) stay verified (sandbox).\n")
w("## 5. Structural findings\n")
w("### 5.1 Agents cannot use the tools (most important integration gap)\n")
w("The 30 agents execute one job type: governed `SCREENING` (`brain.dispatch.run`). Typed tools (`kp.*`, `research.*`, `sandbox.*`, `obs.*`, `media.*`, `pcc.*`, `model.complete`, `voice.status`) are registered and fully gated, but the only production caller of `tools.invoke` is the scheduler; no agent loop selects or calls a tool, and no model is attached. 'Agents can use X' is therefore true of the *interface*, not of running agents. Roadmap M2.\n")
w("### 5.2 Disconnected / hub-bag-only / unreachable modules\n")
hub = [m["file"].split("/")[-1] for m in ss["modules"] if m["invocation"] == "HUB_ADAPTER_BAG_ONLY"]
w("- **%d modules are imported only into `internal-integration-hub` and never invoked:** %s." % (len(hub), ", ".join(hub)))
w("- **Not reachable from runtime/CC/CLI:** `digital-twin.mjs` (4 'working' items downgraded), `evidence-record.mjs` (no caller), `tenant-isolation.mjs` (by design: commercial track, needs Joci's authorization); legacy `supervisor.js`, `worker.js`, `agent-child.js` (LEGACY_START only; `atlasz-competition-v1` policy confined to worker.js).")
w("- Orphans per import scan: %d; entry points with no in-repo caller (CLI/Electron/staging scripts): %s.\n" % (gs["IMPORT_SCAN"], ", ".join(m["file"].split("/")[-1] for m in ss["modules"] if m["invocation"] == "NOT_INVOKED")))
w("### 5.3 Duplicate implementations\n")
w(tbl(["Legacy / standalone module", "Connected counterpart", "Evidence", "Recommendation"], [
 ["`supervisor-safe.qualify()`", "`opportunity-qualification-engine.mjs` (hub bag only)", "The runtime screens leads with its own inline `qualify`; the engine is never called", "Merge: runtime calls the engine, delete the inline copy"],
 ["`deal-state.mjs`, `invoice-engine.mjs`, `delivery-engine.mjs`, `profit-ledger.mjs`, `profit-accounting-engine.mjs`, `payment-confirmation-adapter.mjs`, `follow-up-engine.mjs`, `proposal-quote-engine.mjs`", "`business/{deal-pipeline,invoice-service,delivery-service,finance-intelligence,payment-verification,communication-center}.mjs` (invoked via the Money Engine)", "Two parallel money pipelines; the older addon engines are hub-bag only", "Pick `business/*` as canonical, port any unique rules (e.g. 2/5/10-day follow-up) into it, retire the rest"],
 ["`master-planner-orchestrator.mjs`", "`brain/orchestrator.mjs` + `governed-dispatch`", "Brain orchestrator is invoked; the older planner is hub-bag only", "Retire or fold in"],
 ["`approval-command-gateway.mjs` and `owner-control/approval-gateway.mjs`", "both export `createApprovalGateway`", "One invoked by production code, one via hub hooks", "Single gateway"],
 ["`observability-black-box.mjs`", "`brain/black-box.mjs`", "Brain black box is the invoked, hash-chained one", "Fold in"],
 ["`enterprise-knowledge-agentic-rag.mjs` (in-memory demo)", "`knowledge-projects.mjs` + `research-ledger.mjs`", "Demo is hub-bag only", "Retire after confirming no unique rule"],
 ["`recovery.mjs`, `backup-recovery.mjs`, `owner-control/recovery-points.mjs`, `brain/disaster-recovery.mjs`", "(four recovery modules, all reached)", "Overlapping responsibilities, each invoked", "Document ownership boundaries; avoid a fifth"],
 ["`plugin-manager` / `local-update-adapters` child-process runners", "`code-sandbox.mjs`", "Three separate ways to run child Node code; only the sandbox restricts the filesystem", "Reuse the sandbox runner (see S-04)"],
]))
w("\n### 5.4 Control Center routes and UI\n")
rt = J("docs/audit/route_test_coverage.json"); nt = [r for r, v in rt.items() if v["test_files"] == 0]
w("- 60 routes + 1 root: all authenticated (dynamic probe). 43 nav entries, 29 views + brain views; no broken panel route. `/api/restore/backup` exists server-side but no UI uses it (restore-from-arbitrary-backup has no screen). Routes with no test referencing their handler (static): %s." % (", ".join("`%s`" % r for r in nt) or "none"))
w("- Panels that exist but whose data source is empty by design until providers exist: voice, media (providers), connectors, inbox. On a fresh state every one of these routes answered 200 with no error state (dynamic probe); their NOT_CONNECTED/BLOCKED labelling is covered by the existing tests and was not re-read panel by panel here.\n")
w("### 5.5 Incomplete workflows\n")
w("- Discovery → qualification → proposal → delivery → invoice → payment: each stage is tested in isolation or in a SANDBOX engine; no end-to-end run exists because no search provider, mail connector or payment authority is attached (EXTERNAL / OWNER).")
w("- Lead discovery uses one public source (Hacker News Algolia search, read-only); there are no job-board, mail or CRM connectors. Discovery against the real source was **not exercised** in this audit (no outbound network in the workspace) and has never been verified LIVE; all tests use injected fetchers.")
w("- Scheduler jobs can be created only by code/tests; the Control Center reads but cannot create schedules.")
w("- Voice has never run on real audio; OCR/STT/vision/embedding providers are absent.\n")
w("### 5.6 Security findings (unresolved)\n")
w(tbl(["ID", "Severity", "Finding", "Evidence", "Recommendation"], [
 ["S-01", "MEDIUM", "The runtime HTTP server binds `0.0.0.0` with **no authentication** and serves `/`, `/status`, `/revenue` (full dashboard), `/opportunities` and `/events`.", "supervisor-safe.mjs:428-444; probe: a fresh dashboard is ~24 KB (topology, agent activity, Money Engine aggregates, queue, scheduler, hash-chain heads, lead titles). No raw secrets or personal note text were found in it, but it is information disclosure and every module added to the dashboard widens it.", "M1: `/health` only (minimal) without a token; everything else behind the owner token or removed; add a regression test that the dashboard never contains private content. Do not change Railway until the owner approves."],
 ["S-04", "MEDIUM", "Plugin hook processes and update self-tests are launched as plain `node` children: scrubbed env, timeout and output cap, but **full filesystem and network access** (no `--permission`).", "plugin-manager.mjs:105, local-update-adapters.mjs:102 (code-sandbox.mjs is the only runner with filesystem restriction)", "M1/M6: run them through the sandbox runner with `--permission`; keep owner approval for enabling plugins."],
 ["S-02", "LOW", "`Math.random()` is used as a fallback for ids in tracing-evals, agent-factory and the demo RAG.", "static scan; only used if `crypto.randomUUID` is missing (Node >= 20 always has it)", "Replace with `crypto.randomUUID` / `randomBytes`."],
 ["S-03", "INFO", "No `eval` / `new Function`; no `shell:true`; child-process calls use argument arrays.", "grep over addons, runtime, control-center", "none"],
 ["S-05", "INFO", "Code sandbox is not a container or VM; the Windows installer machine would run PROCESS_ONLY isolation.", "code-sandbox.mjs ISOLATION labels", "M6: evaluate stronger isolation after owner approval."],
 ["S-06", "INFO", "Single-owner model: no delegated roles; voice cannot approve.", "C13, P14 probe", "Keep unless the owner changes the model."],
]))
w("\n## 6. What the %d open items need\n" % rec["open_items"])
need = Counter()
for r in rows:
    if r["final_class"] == "IMPLEMENTED" or r["level"] != "item": continue
    for k in ("required_code", "required_integration", "required_security", "required_tests", "external_dependency", "owner_approval"):
        if r[k]: need[k] += 1
w("Per-item detail for all %d rows (what exists, what code/integration/security/tests are required, external dependency, owner approval, milestone) is in `docs/audit/open_items_detail.csv`. Aggregates over the %d open items:\n" % (rec["registry_rows"], rec["open_items"]))
w(tbl(["Needs", "Open items"], [["Code (build or complete)", need["required_code"]], ["Runtime / UI integration", need["required_integration"]], ["Security review + negative tests", need["required_security"]], ["Tests", need["required_tests"]], ["External dependency (provider, credential, Windows host)", need["external_dependency"]], ["Owner decision / approval", need["owner_approval"]]]))
w("\nThese categories are derived from each row's own blocker/evidence text and the mechanical facts, so they are a **starting specification**, not a design; Task 4 should confirm each against the spec text as it implements it.\n")
w("## 7. Test results and coverage limits\n")
fs = J("docs/audit/full_suite_result.json"); w("- Full suite (`%s`): **%d tests, %d pass, %d fail, %d skipped, %d cancelled** (run after the final documentation regeneration). The same 527 also pass under the coverage run and file-by-file." % (fs["command"], fs["tests"], fs["pass_"], fs["fail"], fs["skipped"], fs["cancelled"]))
w("- Per-file run (`docs/audit/run_tests_per_file.py`): %d files, %d tests, %d pass, %d fail, %d skipped." % (len(tr), tsum("tests"), tsum("pass_"), tsum("fail"), tsum("skipped")))
if cov: w("- Line coverage (node --experimental-test-coverage, full suite, 527/527): **%.1f%% lines / %.1f%% branches** over %d loaded source files; lowest-covered: %s. Absent from the coverage report (not loaded, or not attributed by the collector - e.g. supervisor-safe.mjs is exercised through real-process tests): %s. Caveat: coverage counts executed lines, not asserted behaviour, so it supports but does not prove the 'working' claims (e.g. `negotiation-engine.mjs` is the least covered module and is hub-bag only)." % (cov["lines"], cov["branches"], cov["files"], "; ".join("%s %.0f%%" % (f, p) for f, p in cov["lowest"][:6]), ", ".join(cov["not_loaded_by_any_test"]) or "none"))
w("- Limits: tests run against temp dirs with fake providers, so they show logic and failure handling, not provider behaviour; Windows-only branches (env scrubbing, junctions, process limits) cannot run on this Linux host; the Electron shell and installer are untested here; timing/robustness tests use short real timeouts and can be load-sensitive; mutation testing was done per module by hand-written mutants, not for the whole code base; the registry/gap-register generators have their own tests, so some of the suite verifies tooling rather than product behaviour.")
w("\n## 8. Files produced\n")
w("`docs/audit/` — `static_scan.{py,json}`, `item_audit.{py,json,csv}`, `run_tests_per_file.py`/`test_results.json`, `dynamic_probe.mjs/json`, `independent_probes.mjs/json`, `reclassify.py`, `roadmap.py`, `render_reports.py`, `open_items_detail.csv`, `reconciliation.json`, `roadmap.json`, `route_test_coverage.json`; `docs/registry_item_audit_p7.py` (generated reclassification); updated registry, capability audit and master gap register; `docs/TASK3_ROADMAP.md`.\n")
open(os.path.join(root, "docs/TASK3_AUDIT_REPORT.md"), "w", encoding="utf-8").write("\n".join(P) + "\n")
# ---------------- roadmap
R = ["# ATLASZ V7.3 — Task 3: Prioritised implementation roadmap (input to Task 4)\n",
     "Generated from `docs/audit/roadmap.json` and `docs/audit/open_items_detail.csv`. Counts are **unique outstanding requirements** (PRODUCT + SUPPLEMENTARY, not implemented). Every milestone keeps the 5+25 agent topology, the Security Brain, the control chain and owner approvals, defaults to NO-SPEND, and reports SANDBOX vs LIVE separately. Nothing in this roadmap deploys, spends or touches main/Railway without a separate owner approval.\n",
     "## Order and dependencies\n"]
ordc = {m["id"]: m for m in road}
R.append(tbl(["Milestone", "Name", "Depends on", "Open reqs", "Partial", "Missing", "Ext. blocked", "Owner decision", "Gated by"], [[m["id"], m["name"], ", ".join(m["depends_on"]) or "—", sum(v for k, v in m["open_requirements"].items() if k != "IMPLEMENTED"), m["open_requirements"].get("PARTIAL", 0), m["open_requirements"].get("MISSING", 0), m["open_requirements"].get("EXTERNALLY_BLOCKED", 0), m["open_requirements"].get("AWAITING_OWNER_APPROVAL", 0), m["gates"]] for m in road]))
R.append("\nRecommended execution order: **M1 → M2 → (M3, M6, M8 in parallel) → M4 → M5 → M7 → M9 → M10.** M1 comes first because it removes the only unresolved security exposure and the reliability gaps; M2 comes second because agents currently cannot use any tool, which limits the value of everything built since.\n")
for m in road:
    R.append("## %s — %s\n" % (m["id"], m["name"]))
    R.append("**Scope.** " + m["scope"] + "\n")
    R.append("**Depends on:** " + (", ".join(m["depends_on"]) or "none") + "  |  **External / owner gates:** " + m["gates"] + "\n")
    R.append("**Acceptance criteria.** " + m["acceptance"] + "\n")
    mine = [r for r in rows if r["milestone"] == m["id"] and r["level"] == "item" and r["kind"] in ("PRODUCT_REQUIREMENT", "SUPPLEMENTARY_REQUIREMENT") and r["final_class"] != "IMPLEMENTED"]
    pri = Counter(r["priority"] for r in mine)
    R.append("**Open requirements:** %d (priority mix: %s). Highest-priority items (P0/P1 first):\n" % (len(mine), ", ".join("%s×%d" % kv for kv in sorted(pri.items(), key=lambda kv: str(kv[0])))))
    top = sorted(mine, key=lambda r: (str(r["priority"]), r["id"]))[:12]
    R.append(tbl(["Id", "Class", "Title", "Needs"], [[r["id"], r["final_class"], r["title"][:70].replace("|", "/"), "; ".join(x for x in [("code" if r["required_code"] else ""), ("integration" if r["required_integration"] else ""), ("security" if r["required_security"] else ""), ("tests" if r["required_tests"] else ""), ("EXTERNAL" if r["external_dependency"] else ""), ("OWNER" if r["owner_approval"] else "")] if x)] for r in top]))
    R.append("\nAll rows: filter `open_items_detail.csv` on `milestone == %s`.\n" % m["id"])
R.append("## Cross-cutting rules for Task 4\n")
R.append("- Reuse before building: each milestone starts with the duplicate/hub-bag decisions in the audit report section 5.3 for the modules it touches.\n- A requirement moves to IMPLEMENTED only with: code reachable from a runtime workflow or the Control Center, a passing test that names it, a negative/security test, and a mutation check on the guard. Never LIVE without our own passing probe against the real provider.\n- Externally blocked and owner-gated requirements stay in the roadmap but are built mock-first and labelled; they never count as done.\n- Re-run `docs/audit/*` at the end of each milestone and report before/after counts in the same format as the audit report.\n")
open(os.path.join(root, "docs/TASK3_ROADMAP.md"), "w", encoding="utf-8").write("\n".join(R) + "\n")
print("rendered", len(P), len(R))
