export const DEAL_STATES=["NEW","QUALIFIED","CONTACT_READY","CONTACTED","REPLIED","NEGOTIATING","PROPOSED","AGREED","WON","EXECUTING","QA","DELIVERY_APPROVAL","DELIVERED","INVOICED","AWAITING_PAYMENT","PAID","LOST","BLOCKED"];
const allowed={
NEW:["QUALIFIED","LOST","BLOCKED"],QUALIFIED:["CONTACT_READY","LOST","BLOCKED"],
CONTACT_READY:["CONTACTED","BLOCKED"],CONTACTED:["REPLIED","LOST","BLOCKED"],
REPLIED:["NEGOTIATING","LOST","BLOCKED"],NEGOTIATING:["PROPOSED","LOST","BLOCKED"],
PROPOSED:["AGREED","NEGOTIATING","LOST","BLOCKED"],AGREED:["WON","BLOCKED"],
WON:["EXECUTING","BLOCKED"],EXECUTING:["QA","BLOCKED"],QA:["EXECUTING","DELIVERY_APPROVAL","BLOCKED"],
DELIVERY_APPROVAL:["DELIVERED","EXECUTING","BLOCKED"],DELIVERED:["INVOICED","AWAITING_PAYMENT","BLOCKED"],
INVOICED:["AWAITING_PAYMENT","PAID","BLOCKED"],AWAITING_PAYMENT:["PAID","BLOCKED"],BLOCKED:["NEW","QUALIFIED","CONTACT_READY","CONTACTED","REPLIED","NEGOTIATING","PROPOSED","AGREED","WON","EXECUTING","QA","DELIVERY_APPROVAL","DELIVERED","INVOICED","AWAITING_PAYMENT"]
};
export function transition(deal,next,{ownerApproved=false,paymentConfirmed=false}={}){
 if(!DEAL_STATES.includes(next)) throw new Error("UNKNOWN_DEAL_STATE");
 if(!(allowed[deal.status]||[]).includes(next)) throw new Error("INVALID_DEAL_TRANSITION");
 if(["AGREED","WON","DELIVERY_APPROVAL"].includes(next)&&!ownerApproved) throw new Error("OWNER_APPROVAL_REQUIRED");
 if(next==="PAID"&&!paymentConfirmed) throw new Error("PAYMENT_CONFIRMATION_REQUIRED");
 return {...deal,status:next,updatedAt:new Date().toISOString()};
}
