"""Stage R6 (2026-10-09) notes for docs/capability_audit_data.py. Applied after the R5 overrides.
Rule (unchanged): VERIFIED_WORKING needs functional + integration + negative + mutation tests AND an independent verifier returning VERIFIED with no open MEDIUM/HIGH defect AND the owner's confirmation.
R6 ran three independent rounds against fresh worktrees; each round still found new MEDIUM/HIGH defects (all fixed with regression tests and mutation checks), so NO row is promoted in R6. Statuses stay as in R5;
the evidence and the remaining gap are made precise."""
R6 = "R6 (2026-10-09): 8 independent rounds (fresh worktrees, attack scripts, no access to the authors' tests); all HIGH/MEDIUM findings fixed with regression tests + mutation checks (new mutants killed). NOT promoted: the last round still produced new defects, so the verifier has not returned a clean VERIFIED. "
U = {
 "M12": ("PARTIAL", "Profiles are stored/versioned/validated; R6 CONNECTED them: the selected profile is applied to conversations (conv.create/setProfile, deterministic resolution, [PROFILE] markers neutralised) and to agent tool calls (agent gate: a profile can only NARROW the owner's tool matrix; deleted/tampered/corrupt/emptied store fails closed). Profile create/assign/remove/rollback need the owner passphrase in the Control Center. tests: m12-profile-integration, profiles-hosted, r6-round2. " + R6,
  "Open (documented limits): the profile version hash and the .in-use marker (tenant/agent -> 'profile:last-version-hash') are unkeyed: an attacker who can write BOTH files (or delete the marker and the assignment together) frees an agent; a crash between the store write and the marker write locks the agent out until the owner re-assigns; a profile text is owner-authored prose framed as guidance (marker neutralisation is literal). Independent clean verification pending."),
 "A13": ("PARTIAL", "Connected: a11y.audit route + Control Center panel (authenticated, owner-only, no URL/path input: targets are control-center or supplied text; worker thread with timeout; worker answers validated; incomplete audits never report clean). Findings carry severity/location/remediation; contrast evaluated per theme and per @media/@supports/@container variant; external stylesheets (@import, <link>) make the result INCOMPLETE; HTML checks: input label, button name, duplicate id, aria-hidden focusable. tests: a11y-audit, a11y-control-center, r6-round2. " + R6,
  "Not a WCAG compliance claim: automated checks cover a subset (contrast of declared pairs, a few markup rules). Open: the HTML tokenizer is a hand-written approximation of browser parsing (each independent round found one more parsing quirk; all found so far are fixed, more may exist), so a hostile page can still hide markup from the audit; aria-hidden focusable detection ignores contenteditable/summary/iframe and flags <a> without href (false positives); preload-stylesheet via onload not flagged. Independent clean verification pending."),
 "A08": ("PARTIAL", "All six suggestion sources (approvals, plugin, skill, workflow/tasks, research/ledger, brief) are wired through adapters and tested end to end incl. broker APPROVAL path; normalisation (long ids hashed, invisible/blank titles refused, secrets redacted), dedup + provenance, fairness (priority 4/5 separate allowances, rotation), owner-only dismiss/snooze. tests: suggestions, a08-sources, r6-round2. " + R6,
  "Open (LOW): dedup happens before the mute check (a muted high-priority item can replace an unmuted lower one with the same key); a null snoozed record throws a raw TypeError; the 1000-candidate cap is a documented limit."),
 "M07": ("PARTIAL", "analyst.mjs + analyst.run: cleaning, stats, correlation, charts, reproducible hash, cleaned CSV export (owner), spreadsheet-formula neutralisation, secret scrubbing in headers/labels/titles/steps/errors, row/column caps, malformed ops refused, scalar-only fill values, markdown report neutralises links/images/HTML/pipes. tests: chunker-analyst, analyst-mutation, r6-round2. " + R6,
  "Open (LOW): numeric overflow to Infinity; two headers that scrub to the same text collide in stats keys; bare 'www.' text is only de-linked by a regex. Independent clean verification pending."),
 "GE07": ("PARTIAL", "See M07. Code runs in the sandbox (JS NAMESPACE); the analysis pipeline is analyst.mjs.", "See M07; the Python sandbox native-module escape is NOT resolved (see M06)."),
 "P01": ("PARTIAL", "tutor.mjs + tutor.* ops + Control Center panel. Repeated/early answers cannot raise mastery; accuracy counts only counted answers; broken or out-of-range clocks refused before any mutation (CLOCK_INVALID); hand-edited store shapes (lessons, choices, dueAt, accuracy fields) make the course unreadable instead of crashing or inflating, and an unreadable course is never overwritten (owner can delete it); titles screened for secrets. tests: tutor, stage-r5-fixes, r6-round2. " + R6,
  "Open (LOW): ids and titles are screened for secrets but not for injection text (they are data, never instructions); no content generation without a model."),
 "G12": ("PARTIAL", "SSE feed over the hash-chained Black Box (secrets redacted, client cap, resume, corrupt/junk/forged lines make the stream report SOURCE_UNREADABLE, rotation/truncation reset). R6 junk-line fix. tests: event-stream, r6-round2. " + R6,
  "Open (LOW, documented): a same-size edit with the mtime restored is not noticed by a live tail; rotation to a LONGER log does not send a reset frame; an oversize entry is shown as null-data without the truncated flag."),
 "C01": ("PARTIAL", "code.review / repo analyze / governed test run: many rules (secrets incl. Bearer/JWT/URL credentials/webhooks, eval and indirect eval, child_process, SQL building, TLS off, XSS sinks, path traversal, unsafe deserialisation, shell injection, pipe-to-shell, install scripts), multi-line statements, linear-time on hostile input, closed list of reviewed file types (everything else, incl. extensionless files, makes the verdict INCOMPLETE_REVIEW), test-presence needs real cases, repo-analyzer 'passed' means exit code 0 only. tests: code-review, repo-analyzer, r6-round2. " + R6,
  "Open: no code EDIT workflow (review/test only); MEDIUM-class rule misses remain (eval/exec of non-identifier arguments only reach MEDIUM CHILD_PROCESS_USE; config files (.yml/.json/.toml/.conf) get secret and pipe-to-shell rules only); test-presence is a heuristic that can be inflated by trivial tests."),
 "M08": ("PARTIAL", "Research ledger: a quotation match is QUOTE_MATCHED (lexical: numbers, polarity, term overlap), never VERIFIED; only an owner-passphrase confirmation (bound in the hash chain to claim, relation, retrieval date, quote and source offsets) makes a finding VERIFIED; every event carries a seal of the whole store (questions, findings, contradictions): any store edit outside the ledger turns every finding CONFLICTED (STORE_ALTERED_OUTSIDE_LEDGER) and a tampered store cannot be re-sealed by a new write; finer cross-checks (removed evidence, altered findings/contradictions/questions) remain as defence in depth; non-verifiable or aged refuting sources keep a supported finding CONFLICTED. tests: research-ledger, research-ledger-hosted, r6-round2. " + R6,
  "Open (documented): semantic entailment needs a provider (external); lexical limits (spelled-out numbers, fractions, units, antonyms without a negation word); the chain and head anchor are unkeyed and local (an attacker who can write the store AND the chain AND the head file can forge a consistent state, e.g. roll the ledger back or re-seal to an earlier consistent state); the owner has no way to dismiss a mistaken REFUTES item except by creating a new finding."),
 "C08": ("PARTIAL", "See M08.", "See M08."),
 "GE04": ("PARTIAL", "See M08.", "See M08."),
}
def apply(rows):
    out = []
    for r in rows:
        u = U.get(r[0])
        if u:
            st, ev, miss = u
            r = (r[0], r[1], r[2], r[3], st, ev, miss) + tuple(r[7:])
        out.append(r)
    return out
