# Next continuous build package (84 sections) items, generated from the audited build; statuses change only with new evidence.
def n(i, title, pri, st, loc, tests, ev, blk, nxt):
    return dict(id="ATLASZ-PKG84-"+i, title=title, level="item", section=77, description=title, source="Joci next continuous build package", priority_proposed=pri, dependencies=[], implementation_location=loc,
                status=st, tests=tests, evidence=[ev], blocker=blk, owner_decision=None, strategy="BUILD", status_basis="ITEM_VERIFIED", integration_status="CONNECTED_SANDBOX" if tests else "NOT_CONNECTED", test_status=("TESTED_SANDBOX" if tests else "NOT_TESTED"), classification="SANDBOX", next_action=nxt)
NEW = [
 n('001', 'Agent Factory activation goes through the Agent Governor: unauthorized 31st agent / non-roster identity / unknown capability refused; configure() owner-gated', 'P0', 'EXISTS_AND_WORKING', 'atlasz-addons/agent-factory.mjs; atlasz-addons/owner-control/agent-governor.mjs', ['atlasz-tests/agent-factory-governor.test.mjs'], '7 tests incl. 31st-agent refusal and no-governor BLOCKED', 'SANDBOX only; no live agent creation exists or is allowed', 'Runtime wiring only; fixed 30-agent topology preserved'),
 n('002', 'Update Center protected-component list covers Owner Control and Brain modules', 'P1', 'EXISTS_AND_WORKING', 'atlasz-addons/update-center.mjs', ['atlasz-tests/update-center.test.mjs', 'atlasz-tests/agent-factory-governor.test.mjs'], 'protected list extended with 15 owner-control + 11 brain modules', 'None', 'None'),
 n('003', 'Recovery source mapping: categories mapped to real local sources, vault/secret dirs and symlink escapes refused', 'P1', 'PARTIAL', 'atlasz-addons/owner-control/recovery-source-map.mjs', ['atlasz-tests/agent-factory-governor.test.mjs'], '3 of 7 categories mapped (APPLICATION_VERSION, AGENT_WORKFLOWS, CRITICAL_SYSTEM_STATE); CONFIGURATION, DATABASE_SCHEMA, MODEL_ROUTING, CONNECTOR_CONFIGURATION stay NOT_CONFIGURED', 'No local source exists for 4 categories', 'Map them when config/schema/model-routing/connector stores exist'),
 n('004', 'Internal evidence sources for Independent Verification (job, ledgers, queue, artifact, backup, restore, update, health, black box, approval); external claims stay EXTERNAL_VERIFICATION_REQUIRED', 'P0', 'PARTIAL', 'atlasz-addons/brain/evidence-sources.mjs', ['atlasz-tests/evidence-sources.test.mjs'], '9 tests; unconnected=UNKNOWN; tamper=FAILED_VERIFICATION; UPDATE not connected in runtime', 'No external authority adapters (payment, delivery, message)', 'Connect real adapters when credentials exist'),
 n('005', 'Simulation Lab persistence (config/input/plan/tests/failures/risk/evidence, compare); corrupt store never replaced', 'P1', 'EXISTS_AND_WORKING', 'atlasz-addons/brain/simulation-lab.mjs', ['atlasz-tests/brain-systems.test.mjs'], 'SIM_RECORD_VERSION 2; SIMULATION_STORE_UNREADABLE on corruption', 'None', 'Simulation success is never proof of LIVE success'),
 n('006', 'Memory Fabric over Knowledge Brain, Business Memory, Experience Learning and Entity Graph; tenant isolation; HISTORICAL_RESULT only from independent ACCEPT', 'P1', 'EXISTS_AND_WORKING', 'atlasz-addons/brain/memory-fabric.mjs; atlasz-addons/brain/knowledge-brain.mjs', ['atlasz-tests/memory-fabric.test.mjs'], '8 tests', 'None', 'None'),
 n('007', 'Business engines: universal Job, Artifact Registry, QA Factory, Judge panel, Communication Center, Deal state machine, Delivery, Invoice, Payment Verification, Finance Intelligence with evidence-gated transitions', 'P0', 'PARTIAL', 'atlasz-addons/business/', ['atlasz-tests/business-engines.test.mjs'], '10 tests + mutation checks; SENT/WON/DELIVERED/PAID need evidence; CLAIMED never VERIFIED', 'No live providers or authoritative external adapters; tax rules UNVERIFIED', 'Provide real adapters and credentials (Joci)'),
 n('008', 'SANDBOX Money Engine end-to-end with failure tests at search, outreach, execution, QA, delivery, payment, control, duplicate execution', 'P0', 'PARTIAL', 'atlasz-addons/business/money-engine.mjs', ['atlasz-tests/money-engine-sandbox.test.mjs'], '9 tests; sandbox payment never revenue; LIVE books stay at zero', 'No real SENT/WON/PAID evidence exists; runtime-hosted instance has no adapters', 'Real provider adapters and credentials; hosted in the runtime (LIVE env, no adapters) since this checkpoint'),
 n('009', 'SEARCH pipeline: NORMALIZE/SALES_ACTION stages, source adapters, content-fingerprint dedupe, durable rejection log with reasons, history', 'P0', 'EXISTS_AND_WORKING', 'atlasz-addons/brain/search-pipeline.mjs', ['atlasz-tests/governed-dispatch.test.mjs', 'atlasz-tests/canonical-runtime.test.mjs'], '14 stages; DUPLICATE_CONTENT_OF; SEARCH_STORE_UNREADABLE; sales action is a recommendation only', 'None', 'Runtime builds pipeline without a file (in-memory) by design'),
 n('010', 'Control Center Money Engine / Jobs / Agents panels read persisted engine state (LIVE vs SANDBOX separate, unlabelled never LIVE, corrupt reported)', 'P0', 'PARTIAL', 'atlasz-control-center/money-views.mjs; atlasz-control-center/public/app.js', ['atlasz-tests/control-center-money-views.test.mjs', 'atlasz-tests/money-engine-sandbox.test.mjs'], '5 tests incl. HTTP token protection, sandbox-vs-live separation, mutation check; real sandbox run read back through the view', 'Electron app not run on Windows; no real opportunities/payments recorded yet (hosted engine has no provider adapters)', 'Windows run evidence; provider adapters'),
 n('011', 'Recurring / subscription engine: contract != revenue; activation needs customer-acceptance evidence + owner approval bound to terms; idempotent period invoice DRAFTS; catch-up limit; pause/cancel/price change owner-gated; contracted vs verified recurring revenue kept apart; dunning is recommendation only', 'P1', 'PARTIAL', 'atlasz-addons/business/recurring-billing.mjs', ['atlasz-tests/recurring-billing.test.mjs', 'atlasz-tests/control-center-money-views.test.mjs'], '10 tests + 5 mutation checks (all caught); wired into Money Engine panel and Control Center', 'No external subscription/payment provider; SANDBOX-verified only; tax rules UNVERIFIED', 'Provider adapters; LIVE evidence'),
 n('012', 'Durable tenant-isolated Entity Graph (customers, companies, contacts, opportunities, deals, jobs, documents, communications, invoices, payments, artifacts, agents, subscriptions, follow-ups): typed relations, merge/retire trail, duplicate suggestions, integrity check; Money Engine writes links as the flow happens', 'P0', 'EXISTS_AND_WORKING', 'atlasz-addons/business/entity-graph.mjs; atlasz-addons/brain/brain-system.mjs; atlasz-addons/business/money-engine.mjs', ['atlasz-tests/entity-graph.test.mjs', 'atlasz-tests/money-engine-sandbox.test.mjs', 'atlasz-tests/memory-fabric.test.mjs'], '7 tests + 3 of 4 mutation checks caught (4th equivalent: defence in depth); found and fixed a traversal bug (type filter stopped traversal); replaced the process-global legacy graph in the Brain', 'Control Center graph panel not built', 'Graph panel'),
 n('013', 'CRM core as a view over the Entity Graph and engines: customer 360, pipeline board, history, follow-ups (reminders only), data-quality; stores no customer/deal/money data', 'P1', 'EXISTS_AND_WORKING', 'atlasz-addons/business/crm.mjs', ['atlasz-tests/crm.test.mjs', 'atlasz-tests/money-engine-sandbox.test.mjs'], '5 tests; customer 360 follows engine state with nothing cached; verified against a full sandbox flow', 'No Control Center CRM panel; no external CRM adapter', 'CRM panel'),
 n('014', 'Universal Inbox pipeline RECEIVE>SECURITY SCREEN>CLASSIFY>ENTITY LINK>JOB/DEAL LINK>PRIORITIZE>ROUTE>RECORD: quarantine before reading, verified-id linking, ambiguity reported, reply recorded only with provider evidence, payment messages are claims; hosted in the runtime', 'P0', 'PARTIAL', 'atlasz-addons/business/inbox-pipeline.mjs; atlasz-addons/universal-inbox.mjs; atlasz-runtime/supervisor-safe.mjs', ['atlasz-tests/inbox-pipeline.test.mjs', 'atlasz-tests/money-engine-hosted.test.mjs'], '6 tests + 5 mutation checks (all caught); sources CUSTOMER_REPLY and JOB_INVITATION added', 'No real inbound connector (email etc.); Control Center inbox pipeline view not built; runtime and Control Center both open the inbox chain', 'Authorized inbound connectors; single-writer inbox'),
 n('015', 'Windows test hardening: LF endings, junction symlinks, rm retries, POSIX-signal semantics; CI annotates failing tests', 'P1', 'PARTIAL', 'atlasz-tests/helpers.mjs; .gitattributes; .github/workflows/build-windows-installer.yml', ['atlasz-tests/canonical-runtime.test.mjs', 'atlasz-tests/tenant-isolation.test.mjs'], 'static fixes for likely causes; first CI run failed at the test step and logs are not downloadable from this workspace', 'No Windows run since the fixes; actual failing tests unknown', 'One owner-approved manual workflow run; read failures from annotations'),
]
