# Task 3 reclassification (generated by docs/audit/reclassify.py - do not hand-edit). Statuses are only lowered here; evidence text is preserved.
I = {
 "V73-S13-008": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "V73-S13-009": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "V73-S13-010": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "V73-S13-011": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "V73-S13-012": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "V73-S48-011": {
  "status": "EXISTS_AND_WORKING",
  "implementation_location": "atlasz-addons/owner-control/owner-authority.mjs; atlasz-addons/owner-control/control-chain.mjs",
  "tests": [
   "atlasz-tests/owner-control-core.test.mjs",
   "atlasz-tests/owner-control-bypass.test.mjs"
  ],
  "evidence": [
   "TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - independent probe P04/P05 pass. The standalone guardrail-engine is NOT what enforces this. Previous evidence: TASK3 re-pointed: enforced by the runtime-connected control chain (unknown operations fail closed; SUBSCRIBE/PURCHASE/SIGN_CONTRACT need a signed single-use owner approval; no-spend default) - indepen"
  ],
  "blocker": "SANDBOX evidence only: no real owner key or live channel exercised"
 },
 "ATLASZ-T3-005": {
  "status": "PARTIAL",
  "evidence": [
   "TASK3 downgrade from EXISTS_AND_WORKING: module is imported only into the integration-hub adapter bag and no production workflow invokes it. Unit-level behaviour is tested; it is not part of a running workflow. Previous evidence: Task 4 M1.3: three Math.random fallbacks replaced by node:crypto; static regression guard over all production sources; probe P24"
  ],
  "blocker": "Module tested in isolation; needs a runtime workflow that invokes it (or removal if it duplicates a connected implementation)"
 }
}
