# New (non-V7.3-original) requirement IDs added by Joci's supplementary instructions (2026-10-07) and the follow-up round.
A, T = "atlasz-addons/", "atlasz-tests/"
def n(i, title, pri, st, loc, tests, ev, blk, sec):
    return dict(id=i, title=title, level="item", section=sec, description=title, source="Joci supplementary requirement", priority_proposed=pri, dependencies=[], implementation_location=loc,
                status=st, tests=tests, evidence=ev, blocker=blk, owner_decision=None, strategy="BUILD", status_basis="ITEM_VERIFIED")
NEW = [
 n("ATLASZ-SV-001", "Secret Vault: encrypted at rest, owner-gated set/delete, redaction, rotation", "P0", "EXISTS_AND_WORKING", A+"secret-vault.mjs", [T+"safety-modules.test.mjs"], ["3 tests: AES-GCM, tamper/swap detection, approval gating"], "Host must supply master key; no connector uses it yet", "SAFETY"),
 n("ATLASZ-SV-002", "Safe Mode: system may enter; exit needs signed owner approval + passing self-check; crash-loop protection", "P0", "EXISTS_AND_WORKING", A+"safe-mode.mjs", [T+"safety-modules.test.mjs", T+"canonical-queue-safety.test.mjs"], ["Halts search and screening in the real runtime; survives restart"], None, "SAFETY"),
 n("ATLASZ-SV-003", "Watchdog: stale heartbeat, failing and hanging probes; critical escalation to Safe Mode", "P1", "EXISTS_AND_WORKING", A+"watchdog.mjs", [T+"safety-modules.test.mjs"], ["escalates exactly once; recovery only after healthy observation"], "Registered components: scheduler and queue only", "SAFETY"),
 n("ATLASZ-SV-004", "Startup self-check (environment, durable state, audit chains, topology) -> Safe Mode on FAIL", "P0", "EXISTS_AND_WORKING", A+"startup-self-check.mjs", [T+"safety-modules.test.mjs", T+"canonical-queue-safety.test.mjs"], ["corrupt queue journal -> runtime refuses and enters Safe Mode"], None, "SAFETY"),
 n("ATLASZ-SV-005", "Durable queue/checkpoint wired into the canonical 5+25 runtime", "P0", "EXISTS_AND_WORKING", "atlasz-runtime/supervisor-safe.mjs", [T+"canonical-queue-safety.test.mjs"], ["crash while leased, crash between save and ack, DLQ, mutation-checked"], "Covers screening jobs only", "SAFETY"),
 n("ATLASZ-SV-006", "LIVE/tested flags need probe evidence in connector layer and executor toolbox", "P0", "EXISTS_AND_WORKING", A+"probe-evidence.mjs; universal-connector-layer.mjs; executor-toolbox-registry.mjs", [T+"probe-evidence.test.mjs"], ["bare tested:true refused"], None, "SAFETY"),
 n("ATLASZ-SV-007", "Kill switch enforced at computer-use and model-invocation chokepoints", "P0", "EXISTS_AND_WORKING", A+"computer-use-fabric.mjs; multi-model-brain.mjs", [T+"stop-enforcement.test.mjs"], ["real env-configured process blocked after PAUSE_ALL"], "Future action paths must call the gate", "SAFETY"),
 n("ATLASZ-CC-001", "Windows Control Center desktop app: Electron shell + local token-protected server + UI", "P1", "PARTIAL", "atlasz-control-center/", [T+"control-center.test.mjs"], ["UI exercised in headless Chromium: key creation and PAUSE ALL via dialogs"], "Electron shell never executed and installer never built here (npm registry 403 for electron/electron-builder); not run on Windows", "CONTROL_CENTER"),
 n("ATLASZ-CC-002", "Windows installer (.exe) with desktop ATLASZ icon", "P1", "EXTERNAL_BLOCKER", "atlasz-control-center/scripts/stage-win.mjs; .github/workflows/build-windows-installer.yml", [], ["config + CI workflow written"], "Cannot build in this sandbox; needs GitHub push (not linked) or a Windows build", "CONTROL_CENTER"),
 n("ATLASZ-CC-003", "Owner key store: passphrase-encrypted Ed25519 key on Joci's device", "P0", "EXISTS_AND_WORKING", A+"owner-keystore.mjs", [T+"control-center.test.mjs"], ["encrypted PEM, wrong passphrase refused, no overwrite"], "Protects the file at rest, not against keylogger malware", "CONTROL_CENTER"),
 n("ATLASZ-CC-004", "Control Center owner controls: PAUSE ALL / STOP EXTERNAL / typed Resume / Leave Safe Mode", "P0", "EXISTS_AND_WORKING", "atlasz-control-center/core.mjs", [T+"control-center.test.mjs"], ["real runtime process halted by GUI core and stopped cleanly"], "Local runtime only; remote Railway needs an owner API (production change = Joci approval)", "CONTROL_CENTER"),
 n("ATLASZ-CC-005", "Control Center backup/restore/LKG/recovery drill and System Doctor", "P1", "EXISTS_AND_WORKING", "atlasz-control-center/core.mjs", [T+"control-center.test.mjs"], ["restore needs passphrase-signed approval; doctor detects tampered audit chain"], None, "CONTROL_CENTER"),
 n("ATLASZ-CC-006", "Control Center approval cards (8 mandatory owner questions) with Approve/Reject", "P0", "EXISTS_AND_WORKING", A+"approval-requests.mjs; atlasz-control-center/", [T+"approval-requests.test.mjs"], ["approve signs exactly this request"], "No runtime flow files requests yet", "CONTROL_CENTER"),
 n("ATLASZ-CC-007", "Control Center: Speak-to-Speak / Live Voice panel", "P3", "PARTIAL", "atlasz-control-center/core.mjs; atlasz-control-center/server.mjs; atlasz-control-center/public/app.js (voice)", ["atlasz-tests/voice-conversation-hosted.test.mjs", "atlasz-tests/control-center-systems.test.mjs"], ["Voice panel shows BLOCKED/NOT LIVE honestly, MOCK labelling, transcripts with read, remember and delete"], "EXTERNAL: STT/TTS providers; no push-to-talk control because no audio path exists", "CONTROL_CENTER"),
 n("ATLASZ-CC-008", "Control Center manages local runtime (Start/Stop ATLASZ = start:canonical)", "P1", "EXISTS_AND_WORKING", "atlasz-control-center/core.mjs", [T+"control-center.test.mjs"], ["real process boot, 5+25 topology, SIGTERM exit 0"], "No Windows service / auto-start", "CONTROL_CENTER"),
 n("ATLASZ-REG-001", "Registry integrity test (815 originals kept, allowed statuses, evidence rules, no LIVE)", "P0", "EXISTS_AND_WORKING", "atlasz-tests/registry-integrity.test.mjs", [T+"registry-integrity.test.mjs"], ["5 tests"], None, "REGISTRY"),
]
