# Item-level statuses for S21 (Windows Desktop / Mission Control). Evidence: atlasz-control-center + atlasz-tests/control-center.test.mjs.
A, T, C = "atlasz-addons/", "atlasz-tests/", "atlasz-control-center/"
CC = T+"control-center.test.mjs"
EW, PA, MI, EB = "EXISTS_AND_WORKING", "PARTIAL", "MISSING", "EXTERNAL_BLOCKER"
I = {}
def a(n, st, loc, tests, ev, blk=None): I["V73-S21-%03d" % n] = dict(status=st, implementation_location=loc, tests=tests, evidence=[ev] if ev else [], blocker=blk)
NOELECTRON = "Electron/electron-builder could not be installed here (registry HTTP 403); never built or run on Windows"
a(1, EB, C+"package.json; .github/workflows/build-windows-installer.yml", [], "NSIS build configured and CI workflow written; no installer produced", NOELECTRON)
a(2, PA, "launcher/ATLASZ-Control-Center.cmd; "+C+"package.json", [], "Launcher script exists; NSIS desktop shortcut configured but not built", NOELECTRON)
a(3, PA, "launcher/ATLASZ-Control-Center.cmd; "+C+"electron/main.mjs", [CC], "Server+UI tested in a real process; double-click launch on Windows not run", NOELECTRON)
a(4, PA, C+"server.mjs", [CC], "127.0.0.1 only, per-launch token, Host/Origin checks, CSP, JSON-only bodies tested", "Not run as an installed Windows app")
a(5, PA, C+"core.mjs; "+A+"update-center.mjs", [CC, T+"update-center.test.mjs"], "Auto-update is opt-in and install requires approval; fails closed without adapters", "No real update adapters")
a(6, PA, C+"core.mjs; "+A+"backup-recovery.mjs", [CC, T+"backup-recovery.test.mjs"], "Restore LKG tested in the GUI core", "No installed-app rollback")
a(7, PA, A+"owner-keystore.mjs; "+C+"core.mjs", [CC], "Passphrase-encrypted owner key at rest", "No installed config location on Windows")
a(8, EW, A+"owner-keystore.mjs; "+A+"secret-vault.mjs; "+C+"server.mjs", [CC, T+"safety-modules.test.mjs"], "Tested: private key encrypted on disk, secrets never echoed by HTTP API, vault AES-256-GCM")
a(9, PA, C+"public/style.css", [], "CSS layout verified in headless browser screenshots; no automated responsive test", None)
a(10, EW, C+"core.mjs; server.mjs; public/", [CC], "Core (logic), server (HTTP) and static frontend are separate and each tested through the HTTP API")
a(11, PA, C+"core.mjs", [CC], "Status aggregates runtime /health, self-check, safe mode, queue, emergency", "Not shown from an installed Windows app")
for n, nm in [(12, "Home / MASTER chat"), (13, "Live voice"), (20, "Deals panel"), (23, "Costs panel"), (24, "Profit panel"), (29, "Memory panel"), (30, "Knowledge panel"), (31, "Documents panel"), (32, "Computer Use panel"), (33, "Tax/Accounting panel"), (38, "Settings panel"), (39, "Plugins/Extensions panel"), (40, "Themes/Skins panel")]:
    a(n, MI, None, [], nm + ": no panel in the Control Center" + (" (voice panel says NOT BUILT)" if n == 13 else ""))
a(13, EB, C+"public/app.js", [], "Voice panel states NOT BUILT", "EXTERNAL: STT/TTS provider; not built")
a(14, PA, C+"public/app.js (overview)", [CC], "Runtime, topology, owner key, emergency, safe mode, queue, blockers", None)
a(15, PA, C+"public/app.js (agents)", [CC], "Agent table from runtime dashboard", None)
a(16, PA, C+"public/app.js (agents)", [CC], "5 SEARCH rows; real-process test asserts actualSearch === 5", None)
a(17, PA, C+"public/app.js (agents)", [CC], "25 EXECUTION rows; real-process test asserts actualExecution === 25", None)
a(18, PA, C+"public/app.js (jobs)", [CC], "Opportunity/job list from the runtime; nothing is shown sent or won", None)
a(19, PA, C+"public/app.js (jobs)", [CC], "Opportunities with score/outreach/project state", None)
a(21, PA, C+"public/app.js (money)", [CC], "Counters and confirmed-paid figure", "No payment evidence source, so paid is 0")
a(22, PA, C+"public/app.js (money)", [CC], "Confirmed paid shown separately from candidates/leads", "No payment evidence source")
a(25, EW, C+"public/app.js (approvals); core.mjs", [CC, T+"approval-requests.test.mjs"], "8-field approval cards, signed approve/reject, history; tested through core and HTTP")
a(26, PA, C+"public/app.js (providers)", [CC], "Component health table from runtime status", "No connectors attached")
a(27, PA, C+"public/app.js (providers)", [CC], "Model state PLACEHOLDER_UNCONNECTED/CONNECTED_UNTESTED; LIVE needs probe evidence", "No providers")
a(28, PA, C+"public/app.js (providers)", [CC], "Tool state shown", "No tools probed")
a(34, PA, C+"public/app.js (owner)", [CC], "Owner key, emergency, safe mode, vault state shown", "No dedicated security panel")
a(35, EW, C+"core.mjs (doctor); public/app.js", [CC], "Doctor tested including tamper detection in the audit chain")
a(36, PA, C+"public/app.js (doctor audit chains)", [CC], "Audit-chain integrity shown; no evidence-record browser", None)
a(37, EW, C+"core.mjs; public/app.js (backup)", [CC, T+"backup-recovery.test.mjs"], "Backup, drill, mark LKG, restore LKG, restore backup tested")
a(41, PA, C+"public/app.js (agents)", [CC], "SEARCH state from dashboard", None)
a(42, PA, C+"public/app.js (agents)", [CC], "EXECUTION state from dashboard", None)
a(43, PA, C+"public/app.js (agents)", [CC], "Current task per agent", None)
a(44, PA, C+"public/app.js (overview)", [CC], "ready/done/dead/leased counts", None)
a(45, PA, C+"public/app.js (overview/errors)", [CC], "Blockers table", None)
a(46, PA, C+"public/app.js (errors)", [CC], "Source errors and doctor findings", None)
a(47, PA, C+"public/app.js (providers)", [CC], "Model health table", "No providers")
a(48, PA, C+"public/app.js (providers)", [CC], "Connector health rows if present", "No connectors")
a(49, MI, None, [], "No cost panel; only money counters", None)
a(50, MI, None, [], "No profit panel; money tab shows confirmed paid only", None)
a(51, MI, None, [], "No uptime display", None)
a(52, PA, C+"public/app.js (overview)", [CC], "Watchdog state appears in runtime dashboard; no dedicated panel", None)
a(53, EW, C+"public/app.js (owner); core.mjs", [CC, T+"emergency-stop.test.mjs"], "PAUSE ALL / STOP EXTERNAL red buttons need passphrase; tested incl. real runtime halting; fail-closed", "Owner key must be provisioned")
