# Gaps DISCOVERED by the Task 3 technical audit (docs/TASK3_AUDIT_REPORT.md). All are open (nothing was built in Task 3); evidence points at the audit probe or scan that found them.
def n(i, title, pri, st, loc, tests, ev, blk, sec="TASK3_AUDIT"):
    return dict(id=i, title=title, level="item", section=sec, description=title, source="Task 3 technical audit (2026-10-07)", priority_proposed=pri, dependencies=[], implementation_location=loc,
                status=st, tests=tests, evidence=ev, blocker=blk, owner_decision=None, strategy="BUILD", status_basis="ITEM_VERIFIED")
NEW = [
 n("ATLASZ-T3-001", "Runtime HTTP server (supervisor-safe, binds 0.0.0.0) must not serve the full dashboard, opportunities and events without authentication; only a minimal /health may be open", "P0", "MISSING", "atlasz-runtime/supervisor-safe.mjs:428-444", [], ["Audit probe: a fresh dashboard is ~24 KB (topology, agent activity, Money Engine aggregates, queue, scheduler, hash heads, lead titles) served unauthenticated"], "Changing what is exposed on Railway needs owner approval; code change itself is safe"),
 n("ATLASZ-T3-002", "Plugin hook processes and update self-tests must run through a filesystem- and network-restricted runner (reuse code-sandbox) instead of plain node children", "P1", "MISSING", "atlasz-addons/plugin-manager.mjs:105; atlasz-addons/local-update-adapters.mjs:102", [], ["Both spawn node with scrubbed env, timeout and output cap but no --permission: full filesystem/network access"], "Windows hosts have PROCESS_ONLY isolation only"),
 n("ATLASZ-T3-003", "The 30 agents' governed dispatch must be able to select and invoke typed tools (kp/research/sandbox/obs/media/model) through the control chain", "P0", "MISSING", "atlasz-runtime/supervisor-safe.mjs (runGoverned/execute); atlasz-addons/brain/governed-dispatch.mjs", [], ["Audit scan: the only production caller of tools.invoke is the scheduler; agents run SCREENING jobs only; G06/GE08/P14 downgraded"], "A non-mock model provider is needed for autonomous tool choice (EXTERNAL); deterministic job kinds can be built mock-first"),
 n("ATLASZ-T3-004", "Resolve duplicate and hub-bag-only implementations: 32 modules imported only into internal-integration-hub, the inline qualify() in supervisor-safe, and two createApprovalGateway implementations", "P1", "MISSING", "atlasz-addons/internal-integration-hub.mjs; docs/TASK3_AUDIT_REPORT.md section 5.3", [], ["static_scan.json: 32 HUB_ADAPTER_BAG_ONLY modules; duplicate_exports; qualify() vs opportunity-qualification-engine"], "Each decision (merge/retire) should be recorded per module; no behaviour may be lost"),
 n("ATLASZ-T3-005", "Replace Math.random() id fallbacks with crypto.randomUUID/randomBytes", "P3", "MISSING", "atlasz-addons/tracing-evals.mjs; atlasz-addons/agent-factory.mjs; atlasz-addons/enterprise-knowledge-agentic-rag.mjs", [], ["static_scan.json security: WEAK_RANDOM_FOR_ID_OR_TOKEN x3 (fallback only)"], None),
 n("ATLASZ-T3-006", "Control Center screen for restore-from-backup (/api/restore/backup exists server-side; no UI uses it)", "P2", "MISSING", "atlasz-control-center/server.mjs; atlasz-control-center/public/app.js", [], ["static_scan.json routes: /api/restore/backup used_by_ui=false"], "Restore is destructive: needs owner approval UX and a drill first"),
 n("ATLASZ-T3-007", "Add handler tests for Control Center routes without any test reference: /api/opportunities, /api/money-recurring, /api/backup, /api/updates/auto", "P2", "MISSING", "atlasz-control-center/server.mjs", [], ["docs/audit/route_test_coverage.json: 4 of 61 handlers have no test reference"], None),
 n("ATLASZ-T3-008", "Control Center cannot create scheduled jobs (it reads the persisted schedule only)", "P2", "MISSING", "atlasz-addons/scheduler.mjs; atlasz-control-center/core.mjs", [], ["Audit scan of C12 integration gaps; no schedule-creation route in server.mjs"], "External-effect jobs must keep requiring signed owner approval"),
 n("ATLASZ-T3-009", "Real-source verification of lead discovery (Hacker News Algolia read) and of every other external read: our own probe must pass before any LIVE claim", "P2", "EXTERNAL_BLOCKER", "atlasz-runtime/supervisor-safe.mjs:219-231", [], ["All tests inject fetchers; the workspace has no outbound network, so real discovery was never exercised"], "Needs outbound network and an owner-approved source list"),
]
